version: '3.3'

services:
   api1:
     build: ./application/
     container_name: api1
     ports:
       - "8081:8080"
     environment:
       - MESSAGE=First
     volumes:
       - ./application/:/usr/src/app/
   api2:
     build: ./application/
     container_name: api2
     ports:
       - "8082:8080"
     environment:
       - MESSAGE=Second
     volumes:
       - ./application/:/usr/src/app/
   api3:
     build: ./application/
     container_name: api3
     ports:
       - "8083:8080"
     environment:
       - MESSAGE=Third
     volumes:
       - ./application/:/usr/src/app/
   proxyn:
     build: ./nginx-docker/
     container_name: proxyn
     ports:
        - "8080:80"